import {sceneList} from './lists.js';
import {parseSource,uid} from './parser.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={projects:[],active:null},draft=null,tab='scenes',history=[],assignment=null;
try{state=JSON.parse(localStorage.getItem('estudio-v1'))||state;}catch{toast('No se pudo leer el guardado. Importa un respaldo si lo tienes.');}
const project=()=>state.projects.find(p=>p.id===state.active);
function askName(title,value){return new Promise(resolve=>{const dialog=document.createElement('dialog');dialog.innerHTML=`<form method="dialog"><h2>${esc(title)}</h2><label>Nombre<input name="projectName" value="${esc(value)}" required autofocus></label><footer><button value="cancel" formnovalidate>Cancelar</button><button class="primary" value="ok">Guardar</button></footer></form>`;document.body.append(dialog);dialog.onclose=()=>{resolve(dialog.returnValue==='ok'?dialog.querySelector('input').value:null);dialog.remove();};dialog.showModal();});}
const target=()=>draft||project();
function toast(msg){$('#toast').textContent=msg;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',3500);}
function save(){try{localStorage.setItem('estudio-v1',JSON.stringify(state));$('.save')&&($('.save').textContent='Guardado en este navegador');}catch{toast('No se pudo guardar: exporta un respaldo para conservar los cambios.');}}
function snapshot(){history.push({draft:!!draft,data:structuredClone(target())});if(history.length>30)history.shift();}
function undo(){const h=history.pop();if(!h)return;if(h.draft){draft=h.data;review();}else{const i=state.projects.findIndex(p=>p.id===h.data.id);state.projects[i]=h.data;save();render();}toast('Cambio deshecho');}
const theme=localStorage.getItem('estudio-theme')||'system';
function applyTheme(t){document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t;}
applyTheme(theme);matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>applyTheme(localStorage.getItem('estudio-theme')||'system'));
async function newProject(){const name=await askName('Nuevo proyecto','Mi nuevo proyecto');if(!name?.trim())return;const p={id:uid(),name:name.trim(),scenes:[],characters:[],unknown:[],sources:[],lastScene:0,showCharacters:false};state.projects.push(p);state.active=p.id;history=[];save();render();}
function progress(s){return s.imageDone&&s.videoDone?'✓':s.imageDone||s.videoDone?'◐':'○';}
let characterIndex=0;
function sceneView(p,s){return `<nav class="scene-nav" aria-label="Elegir escena">${p.scenes.map((x,i)=>`<button class="circle ${s?.id===x.id?'active':''}" data-scene="${i}" title="${esc(x.name)}: ${progress(x)==='✓'?'completo':progress(x)==='◐'?'parcial':'pendiente'}">${i+1}<small>${progress(x)}</small></button>`).join('')}<button id="addScene">＋ Escena</button></nav>${s?`<div class="scene-heading row"><h2 title="${esc(s.name)}">${esc(s.name)}</h2>${metadataButton(s)}</div><div class="panels">${panel(s,'image','Prompt de imagen')}${panel(s,'video','Prompt de video')}</div><footer class="workspace-footer"><span class="muted">○ Pendiente · ◐ Parcial · ✓ Completo</span><div class="row"><button id="prev" ${p.lastScene===0?'disabled':''}>← Anterior</button><span class="scene-count">${p.lastScene+1} / ${p.scenes.length}</span><button id="next" ${p.lastScene>=p.scenes.length-1?'disabled':''}>Siguiente →</button></div></footer>`:empty('Tu primera escena empieza aquí','Pega una respuesta o crea una escena vacía.')}`;}
function characterView(p){characterIndex=Math.min(characterIndex,Math.max(0,p.characters.length-1));const c=p.characters[characterIndex];return `<div class="character-toolbar row"><div class="character-buttons" role="toolbar" aria-label="Elegir personaje">${p.characters.map((x,i)=>`<button data-character-select="${i}" aria-pressed="${i===characterIndex}" class="${i===characterIndex?'active':''}" title="${esc(x.name)}">${esc(x.name.replace(/^Personaje\s+\d+\s*·\s*/i,''))}</button>`).join('')}</div><button id="addCharacter">＋ Personaje</button></div>${c?`<section class="panel character" data-character="${c.id}"><header><input aria-label="Nombre del personaje" data-character-name="${c.id}" value="${esc(c.name)}"><div class="row">${metadataButton(c)}<button data-copy-character="${c.id}" class="primary">Copiar</button></div></header><textarea aria-label="Prompt del personaje" data-character-prompt="${c.id}">${esc(c.prompt)}</textarea><footer><span class="muted">${characterIndex+1} de ${p.characters.length} personajes</span><button data-character-action="${c.id}">Acciones</button></footer></section>`:empty('Aún no hay personajes','Añade un personaje o importa una respuesta.')}`;}
function listView(p){return `<div class="panels list-panels">${[['image','Texto a imagen'],['video','Imagen a video']].map(([kind,title])=>{const list=sceneList(p.scenes,kind);return `<section class="panel list-panel"><header><h2>${title}</h2><button class="primary" data-copy-list="${kind}" aria-label="Copiar toda la lista de ${title.toLowerCase()}" ${!list.count?'disabled':''}>Copiar toda la lista</button></header><p class="list-summary">${list.count} prompts${list.missing.length?` · Sin prompt: ${list.missing.join(', ')}`:''}</p><textarea readonly wrap="off" data-list="${kind}" aria-label="Lista ${title.toLowerCase()}" placeholder="No hay prompts de este tipo.">${esc(list.text)}</textarea><footer><span class="muted">Una línea por prompt · Edita en Escenas</span></footer></section>`;}).join('')}</div>`;}
function pendingView(p){return `<div class="empty review-home"><div class="symbol">▤</div><h2>Revisión y fuente original</h2><p>${p.unknown.length} bloques pendientes · ${p.sources.length} respuestas conservadas</p><button class="primary" id="openInspection">Abrir revisión y fuentes</button><label class="check"><input id="showCharacters" type="checkbox" ${p.showCharacters?'checked':''}> Mostrar pestaña Personajes</label><p class="muted">Puedes asignar texto, consultar la fuente y deshacer cambios.</p></div>`;}
function render(){const p=project(),s=p?.scenes[p.lastScene||0];$('#app').innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><span>✦</span>Estudio<button id="closeLibrary" aria-label="Cerrar biblioteca">✕</button></div><button class="primary" id="newProject">＋ Nuevo proyecto</button><div class="eyebrow">TU BIBLIOTECA</div><div class="project-list">${state.projects.map(x=>`<button class="project ${p?.id===x.id?'active':''}" data-project="${x.id}">${esc(x.name)}<br><small class="muted">${x.scenes.length} escenas · ${x.characters.length} personajes</small></button>`).join('')}</div><div class="bottom"><select id="theme" aria-label="Tema"><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></select><p class="save">Guardado en este navegador</p><div class="backup-actions"><button id="export">Exportar respaldo</button><button id="importBackup">Importar respaldo</button></div><input type="file" id="backupFile" accept=".json" hidden></div></aside><main><div class="top"><button id="openLibrary" aria-label="Abrir biblioteca">☰</button><h1 title="${esc(p?.name||'Estudio de prompts')}">${esc(p?.name||'Estudio de prompts')}</h1>${p?`<div class="row"><button id="rename">Renombrar</button><button class="primary" id="openImport">＋ Pegar respuesta</button></div>`:''}</div>${p?`<div class="tabs"><button data-tab="scenes" class="${tab==='scenes'?'active':''}">Escenas <span class="pill">${p.scenes.length}</span></button><button data-tab="lists" class="${tab==='lists'?'active':''}">Escenas en lista</button>${p.showCharacters?`<button data-tab="characters" class="${tab==='characters'?'active':''}">Personajes <span class="pill">${p.characters.length}</span></button>`:''}<button data-tab="pending" class="${tab==='pending'?'active':''}">Revisión ${p.unknown.length?'· '+p.unknown.length:''}</button><button id="undo" ${!history.some(h=>!h.draft)?'disabled':''}>↶ Deshacer</button></div><section class="workspace ${tab==='scenes'?'scene-workspace':tab==='characters'?'character-workspace':'review-workspace'}">${tab==='scenes'?sceneView(p,s):tab==='characters'?characterView(p):tab==='lists'?listView(p):pendingView(p)}</section>`:empty('Un lugar para todos tus prompts','Crea un proyecto para organizar personajes y escenas.','<button class="primary" id="start">Crear mi primer proyecto</button>')}</main></div>`;
 $('#openLibrary').onclick=()=>$('.sidebar').classList.add('is-open');$('#closeLibrary').onclick=()=>$('.sidebar').classList.remove('is-open');
 document.querySelectorAll('[data-character-select]').forEach(b=>{const choose=index=>{const offset=$('.character-buttons').scrollLeft;characterIndex=index;render();const bar=$('.character-buttons'),active=bar.querySelector(`[data-character-select="${index}"]`);bar.scrollLeft=offset;active.focus({preventScroll:true});active.scrollIntoView({block:'nearest',inline:'nearest'});};b.onclick=()=>choose(+b.dataset.characterSelect);b.onkeydown=e=>{let index=+b.dataset.characterSelect;if(e.key==='ArrowRight')index=(index+1)%p.characters.length;else if(e.key==='ArrowLeft')index=(index+p.characters.length-1)%p.characters.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=p.characters.length-1;else return;e.preventDefault();choose(index);};});
 document.querySelectorAll('[data-metadata]').forEach(b=>b.onclick=()=>{const item=[...p.scenes,...p.characters].find(x=>x.id===b.dataset.metadata);showInformation('Metadatos · '+item.name,`<pre class="information-text">${esc(item.metadata)}</pre>`);});
 document.querySelectorAll('[data-copy-list]').forEach(b=>b.onclick=()=>copy(sceneList(p.scenes,b.dataset.copyList).text,'Lista copiada'));
 $('#openInspection')&&($('#openInspection').onclick=openInspection);
 if($('#inspectionDialog')?.open)openInspection(false);
 $('#theme').value=localStorage.getItem('estudio-theme')||'system';$('#theme').onchange=e=>{localStorage.setItem('estudio-theme',e.target.value);applyTheme(e.target.value);};$('#newProject').onclick=newProject;$('#start')&&($('#start').onclick=newProject);
 document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{state.active=b.dataset.project;tab='scenes';history=[];save();render();});
 $('#export').onclick=()=>{const a=document.createElement('a');const url=URL.createObjectURL(new Blob([JSON.stringify({version:1,...state},null,2)],{type:'application/json'}));a.href=url;a.download='estudio-respaldo.json';a.click();URL.revokeObjectURL(url);};$('#importBackup').onclick=()=>$('#backupFile').click();$('#backupFile').onchange=importBackup;
 if(!p)return;$('#rename').onclick=async()=>{const n=await askName('Renombrar proyecto',p.name);if(n?.trim()){p.name=n.trim();save();render();}};
 $('#openImport').onclick=()=>{draft=null;history=[];$('#review').innerHTML='';$('#sourceInput').value='';$('#importDialog').showModal();};
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();});$('#undo').onclick=undo;
 document.querySelectorAll('[data-scene]').forEach(b=>b.onclick=()=>{p.lastScene=+b.dataset.scene;save();render();});
 $('#addScene')&&($('#addScene').onclick=()=>{p.scenes.push(makeScene(p.scenes.length+1));p.lastScene=p.scenes.length-1;save();render();});
 for(const [id,delta] of [['prev',-1],['next',1]])if($('#'+id))$('#'+id).onclick=()=>{p.lastScene+=delta;save();render();};
 document.querySelectorAll('[data-prompt]').forEach(t=>{t.oninput=()=>{s[t.dataset.prompt]=t.value;s[t.dataset.prompt+'Done']=false;save();const check=$(`[data-done="${t.dataset.prompt}"]`);check.checked=false; $(`[data-status="${t.dataset.prompt}"]`).textContent="○ Pendiente"; $(`[data-scene="${p.lastScene}"] small`).textContent=progress(s);};t.oncontextmenu=e=>{e.preventDefault();openAssignment({type:'prompt',scene:s.id,kind:t.dataset.prompt,start:t.selectionStart,end:t.selectionEnd,text:t.selectionStart!==t.selectionEnd?t.value.slice(t.selectionStart,t.selectionEnd):t.value});};});
 document.querySelectorAll('[data-done]').forEach(c=>c.onchange=()=>{s[c.dataset.done+'Done']=c.checked;save();render();});document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copy(s[b.dataset.copy]));
 document.querySelectorAll('[data-prompt-action]').forEach(b=>b.onclick=()=>{const t=$(`[data-prompt="${b.dataset.promptAction}"]`);openAssignment({type:'prompt',scene:s.id,kind:b.dataset.promptAction,start:t.selectionStart,end:t.selectionEnd,text:t.selectionStart!==t.selectionEnd?t.value.slice(t.selectionStart,t.selectionEnd):t.value});});
 $('#addCharacter')&&($('#addCharacter').onclick=()=>{p.characters.push({id:uid(),name:'Nuevo personaje',prompt:''});save();render();});
 document.querySelectorAll('[data-character-name]').forEach(t=>t.oninput=()=>{p.characters.find(c=>c.id===t.dataset.characterName).name=t.value;const button=$(`[data-character-select="${characterIndex}"]`);button.textContent=t.value.replace(/^Personaje\s+\d+\s*·\s*/i,'');button.title=t.value;save();});document.querySelectorAll('[data-character-prompt]').forEach(t=>t.oninput=()=>{p.characters.find(c=>c.id===t.dataset.characterPrompt).prompt=t.value;save();});document.querySelectorAll('[data-copy-character]').forEach(b=>b.onclick=()=>copy(p.characters.find(c=>c.id===b.dataset.copyCharacter).prompt));
 document.querySelectorAll('[data-character-action]').forEach(b=>b.onclick=()=>selectCharacter(b.dataset.characterAction));document.querySelectorAll('[data-character]').forEach(b=>b.oncontextmenu=e=>{e.preventDefault();selectCharacter(b.dataset.character);});
 $('#showCharacters')&&($('#showCharacters').onchange=e=>{p.showCharacters=e.target.checked;save();render();});bindUnknown();
}
function metadataButton(item){return item.metadata?.trim()?`<button data-metadata="${item.id}">Metadatos</button>`:'';}
function informationDialog(id){let dialog=$('#'+id);if(!dialog){dialog=document.createElement('dialog');dialog.id=id;dialog.className='information-dialog';document.body.append(dialog);}return dialog;}
function showInformation(title,body){const dialog=informationDialog('informationDialog');dialog.innerHTML=`<form method="dialog"><header><h2>${esc(title)}</h2><button aria-label="Cerrar información">✕</button></header></form><div class="information-body">${body}</div>`;dialog.showModal();}
function openInspection(open=true){const p=project(),dialog=informationDialog('inspectionDialog');dialog.innerHTML=`<form method="dialog"><header><h2>Revisión y fuentes</h2><div class="row"><button type="button" id="inspectionUndo">↶ Deshacer</button><button aria-label="Cerrar revisión">✕</button></div></header></form><p>Selecciona texto o usa Acciones para asignarlo. La fuente original se conserva.</p><div class="inspection-body">${unknownHTML(p)}${p.sources.map((src,i)=>`<details><summary>Fuente original ${i+1}</summary><pre>${esc(src)}</pre></details>`).join('')}</div>`;bindUnknown(); const undoButton=dialog.querySelector("#inspectionUndo");undoButton.disabled=!history.some(h=>!h.draft);undoButton.onclick=undo;if(open)dialog.showModal();}
function metadataHTML(item){return item.metadata?.trim()?`<details class="metadata"><summary>Metadatos · ${esc(item.name)}</summary><pre>${esc(item.metadata)}</pre></details>`:'';}
function empty(title,desc,action=''){return `<div class="empty"><div class="symbol">▤</div><h1>${title}</h1><p>${desc}</p>${action}</div>`;}
function panel(s,kind,title){return `<section class="panel"><header><h2>${title}</h2><button class="primary" data-copy="${kind}">Copiar</button></header><span class="pill" data-status="${kind}">${s[kind+'Done']?'✓ Completado':'○ Pendiente'}</span><textarea data-prompt="${kind}" aria-label="${title}" placeholder="Escribe o asigna un prompt…">${esc(s[kind])}</textarea><footer><label class="check"><input aria-label="Generación de ${kind==='image'?'imagen':'video'} completada" type="checkbox" data-done="${kind}" ${s[kind+'Done']?'checked':''}> Generación completada</label><button data-prompt-action="${kind}">Acciones</button></footer></section>`;}
function unknownHTML(p){return p.unknown.length?p.unknown.map(u=>`<div class="unknown" data-unknown="${u.id}"><header><strong>No reconocido</strong><button data-unknown-action="${u.id}">Acciones</button></header><pre>${esc(u.text)}</pre></div>`).join(''):'<p>✓ No hay contenido pendiente de asignar.</p>';}
function bindUnknown(){document.querySelectorAll('[data-unknown-action]').forEach(b=>b.onclick=()=>selectUnknown(b.dataset.unknownAction));document.querySelectorAll('[data-unknown]').forEach(b=>b.oncontextmenu=e=>{e.preventDefault();selectUnknown(b.dataset.unknown);});}
function selectUnknown(id){const u=target().unknown.find(u=>u.id===id);const selection=window.getSelection();const root=$('#importDialog').open?$('#review'):$('#inspectionDialog')?.open?$('#inspectionDialog'):$('#app');const pre=root.querySelector(`[data-unknown="${id}"] pre`);let text=u.text,start=0,end=text.length;if(selection?.rangeCount&&pre.contains(selection.anchorNode)&&pre.contains(selection.focusNode)&&selection.toString()){const r=selection.getRangeAt(0),before=r.cloneRange();before.selectNodeContents(pre);before.setEnd(r.startContainer,r.startOffset);start=before.toString().length;text=r.toString();end=start+text.length;}openAssignment({type:'unknown',id,text,start,end});}
function makeScene(n,name){return {id:uid(),number:n,name:name||'Escena '+n,image:'',video:'',imageDone:false,videoDone:false};}
function selectCharacter(id){const t=$(`[data-character-prompt="${id}"]`);openAssignment({type:'character',id,start:t.selectionStart,end:t.selectionEnd,text:t.selectionStart!==t.selectionEnd?t.value.slice(t.selectionStart,t.selectionEnd):t.value});}
function openAssignment(a){if(!a.text){toast('Selecciona o escribe contenido primero');return;}assignment=a;$('#assignScene').innerHTML=target().scenes.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')+'<option value="new">Crear nueva escena</option>';$('#assignKind').value='image';$('#assignName').value='';$('#assignmentNote').textContent='Se moverá el contenido seleccionado. Puedes deshacer esta acción.';$('#assignDialog').showModal();}
$('#cancelAssign').onclick=()=>$('#assignDialog').close();
$('#confirmAssign').onclick=()=>{const p=target(),a=assignment,kind=$('#assignKind').value; snapshot();let dest;if(kind==='image'||kind==='video'){dest=p.scenes.find(s=>s.id===$('#assignScene').value);if(!dest){dest=makeScene(p.scenes.length+1,$('#assignName').value.trim());p.scenes.push(dest);}}
 if(a.type==='unknown'){const u=p.unknown.find(u=>u.id===a.id);u.text=u.text.slice(0,a.start)+u.text.slice(a.end);if(!u.text.trim())p.unknown=p.unknown.filter(u=>u.id!==a.id);}else if(a.type==='character'){const c=p.characters.find(c=>c.id===a.id);if(a.start===a.end){p.characters=p.characters.filter(c=>c.id!==a.id);}else c.prompt=c.prompt.slice(0,a.start)+c.prompt.slice(a.end);}else{const s=p.scenes.find(s=>s.id===a.scene);const end=a.start===a.end?s[a.kind].length:a.end;const start=a.start===a.end?0:a.start;s[a.kind]=s[a.kind].slice(0,start)+s[a.kind].slice(end);s[a.kind+'Done']=false;}
 if(kind==='character'){p.characters.push({id:uid(),name:$('#assignName').value.trim()||'Personaje '+(p.characters.length+1),prompt:a.text});p.showCharacters=true;}
 if(dest){dest[kind]=$('#assignMode').value==='replace'?a.text:dest[kind]+(dest[kind]?'\n\n':'')+a.text;dest[kind+'Done']=false;}
 $('#assignDialog').close();if(draft)review();else{save();render();}toast(kind==='delete'?'Contenido eliminado. Deshacer disponible.':'Contenido asignado');};
$('#organize').onclick=()=>{if(!$('#sourceInput').value.trim()){toast('Pega una respuesta primero');return;}draft=parseSource($('#sourceInput').value);history=[];review();};
$('#importDialog').addEventListener('close',()=>{draft=null;history=history.filter(h=>!h.draft);});
function review(){const d=draft;$('#review').innerHTML=`<div class="review-summary"><strong>Revisa antes de importar</strong><p>${d.scenes.length} escenas · ${d.characters.length} personajes · ${d.unknown.length} bloques no reconocidos</p></div>${d.characters.map(c=>`<details><summary>${esc(c.name)}</summary>${metadataHTML(c)}<h3>Prompt del personaje</h3><pre>${esc(c.prompt)}</pre></details>`).join('')}${d.scenes.map(s=>`<details open><summary>${esc(s.name)}</summary>${metadataHTML(s)}<h3>Imagen</h3><pre>${esc(s.image)||'Sin prompt'}</pre><h3>Video</h3><pre>${esc(s.video)||'Sin prompt'}</pre></details>`).join('')}${unknownHTML(d)}<details><summary>Fuente completa original</summary><pre>${esc(d.source)}</pre></details><footer><button id="reviewUndo" ${!history.length?'disabled':''}>↶ Deshacer</button><button class="primary" id="confirmImport">Confirmar importación</button></footer>`;bindUnknown();$('#reviewUndo').onclick=undo;$('#confirmImport').onclick=()=>{const p=project();snapshot();p.scenes.push(...d.scenes);p.characters.push(...d.characters);p.unknown.push(...d.unknown);p.sources.push(d.source);p.showCharacters=p.showCharacters||d.characters.length>0;draft=null;history=[];save();$('#importDialog').close();tab='scenes';render();toast('Importación guardada; fuente original conservada');};}
async function copy(text,message='Prompt copiado'){try{await navigator.clipboard.writeText(text);toast(message);}catch{toast('No se pudo copiar. Selecciona el texto y usa Ctrl+C.');}}
function validProject(p){return p&&typeof p.id==='string'&&typeof p.name==='string'&&Array.isArray(p.sources)&&p.sources.every(s=>typeof s==='string')&&Array.isArray(p.scenes)&&p.scenes.every(s=>s&&typeof s.id==='string'&&typeof s.name==='string'&&typeof s.image==='string'&&typeof s.video==='string')&&Array.isArray(p.characters)&&p.characters.every(c=>c&&typeof c.id==='string'&&typeof c.name==='string'&&typeof c.prompt==='string')&&Array.isArray(p.unknown)&&p.unknown.every(u=>u&&typeof u.id==='string'&&typeof u.text==='string');}
async function importBackup(e){try{const data=JSON.parse(await e.target.files[0].text());if(data.version!==1||!Array.isArray(data.projects)||!data.projects.every(validProject))throw Error();for(const p of data.projects){p.id=uid();p.lastScene=Math.max(0,Math.min(Number(p.lastScene)||0,p.scenes.length-1));state.projects.push(p);}if(data.projects.length)state.active=data.projects[0].id;history=[];save();render();toast('Respaldo añadido a tu biblioteca');}catch{toast('Respaldo inválido. No se modificaron tus proyectos.');}}
render();





